export interface Opportunity {
  id: string
  branchCode: number
  name: string
  province: string
  department: "SAPS" | "Health" | "Education" | "Correctional Services" | "SANDF" | "Other"
  latitude: number
  longitude: number
  distance: number
  employees: string
  minEmployees: number
  maxEmployees: number
  currentPenetration: number
  lastVisit: string | null
  visitStatus: "Visit Scheduled" | "Follow-up Required" | "Completed" | "New"
  strategicValue: "High" | "Medium" | "Low"
  keyChallenge: string
  agentAction: string
  aiInsight: string
}

export const opportunities: Opportunity[] = [
  // 708: Bellville
  {
    id: "opp-708-1",
    branchCode: 708,
    name: "SAPS Khayelitsha",
    province: "Western Cape",
    department: "SAPS",
    latitude: -34.024,
    longitude: 18.665,
    distance: 20.5,
    employees: "400 - 450",
    minEmployees: 400,
    maxEmployees: 450,
    currentPenetration: 85,
    lastVisit: "2025-07-15",
    visitStatus: "Follow-up Required",
    strategicValue: "High",
    keyChallenge: "Strict Access",
    agentAction: "Deepen existing relationships",
    aiInsight:
      "With ~19% penetration, there's still significant room for growth. Leverage existing clients for referrals.",
  },
  {
    id: "opp-708-2",
    branchCode: 708,
    name: "Tygerberg Hospital",
    province: "Western Cape",
    department: "Health",
    latitude: -33.914,
    longitude: 18.61,
    distance: 5.2,
    employees: "2500+",
    minEmployees: 2500,
    maxEmployees: 3000,
    currentPenetration: 310,
    lastVisit: "2025-07-10",
    visitStatus: "Completed",
    strategicValue: "High",
    keyChallenge: "Large, complex site",
    agentAction: "Segment by ward/department",
    aiInsight: "A massive captive audience. Penetration is ~10%. Focus on specific hospital wings or staff roles.",
  },
  {
    id: "opp-708-3",
    branchCode: 708,
    name: "Bellville Magistrate's Court",
    province: "Western Cape",
    department: "Other",
    latitude: -33.903,
    longitude: 18.63,
    distance: 1.5,
    employees: "150-200",
    minEmployees: 150,
    maxEmployees: 200,
    currentPenetration: 35,
    lastVisit: "2025-07-22",
    visitStatus: "Visit Scheduled",
    strategicValue: "Medium",
    keyChallenge: "Legal Professionals",
    agentAction: "Offer tailored financial wellness",
    aiInsight: "Justice department staff. High income, good potential. Focus on investment-linked products.",
  },
  {
    id: "opp-708-4",
    branchCode: 708,
    name: "SAPS Kuilsrivier",
    province: "Western Cape",
    department: "SAPS",
    latitude: -33.932,
    longitude: 18.682,
    distance: 12.8,
    employees: "200-250",
    minEmployees: 200,
    maxEmployees: 250,
    currentPenetration: 95,
    lastVisit: "2025-06-28",
    visitStatus: "Completed",
    strategicValue: "Medium",
    keyChallenge: "High Saturation",
    agentAction: "Maintain presence & service",
    aiInsight: "High penetration at ~38%. Shift focus from acquisition to service and retention.",
  },
  {
    id: "opp-708-5",
    branchCode: 708,
    name: "Cape Peninsula University of Technology",
    province: "Western Cape",
    department: "Education",
    latitude: -33.931,
    longitude: 18.639,
    distance: 2.1,
    employees: "1000+",
    minEmployees: 1000,
    maxEmployees: 1200,
    currentPenetration: 80,
    lastVisit: "2025-07-01",
    visitStatus: "Follow-up Required",
    strategicValue: "High",
    keyChallenge: "Academic Calendar",
    agentAction: "Target staff during term time",
    aiInsight: "Large academic staff base. Target pre-holiday periods for travel-related loan purposes.",
  },
  // 743: Bloemfontein
  {
    id: "opp-743-1",
    branchCode: 743,
    name: "Pelonomi Hospital",
    province: "Free State",
    department: "Health",
    latitude: -29.133,
    longitude: 26.215,
    distance: 3.5,
    employees: "1500+",
    minEmployees: 1500,
    maxEmployees: 1800,
    currentPenetration: 120,
    lastVisit: null,
    visitStatus: "New",
    strategicValue: "High",
    keyChallenge: "Large staff base",
    agentAction: "Establish initial contact",
    aiInsight: "Major healthcare hub for the region. A key target for establishing a strong health sector presence.",
  },
  {
    id: "opp-743-2",
    branchCode: 743,
    name: "SAPS Park Road",
    province: "Free State",
    department: "SAPS",
    latitude: -29.116,
    longitude: 26.211,
    distance: 1.2,
    employees: "300-350",
    minEmployees: 300,
    maxEmployees: 350,
    currentPenetration: 45,
    lastVisit: "2025-07-11",
    visitStatus: "Follow-up Required",
    strategicValue: "Medium",
    keyChallenge: "CBD Location",
    agentAction: "Target shift changes",
    aiInsight: "Central police station with high traffic. Good opportunity for consistent, daily engagement.",
  },
  {
    id: "opp-743-3",
    branchCode: 743,
    name: "Free State Dept. of Education",
    province: "Free State",
    department: "Education",
    latitude: -29.118,
    longitude: 26.223,
    distance: 2.0,
    employees: "500-600",
    minEmployees: 500,
    maxEmployees: 600,
    currentPenetration: 60,
    lastVisit: null,
    visitStatus: "New",
    strategicValue: "High",
    keyChallenge: "Admin Staff",
    agentAction: "Focus on office hours",
    aiInsight: "Provincial admin hub for education. Target lunch hours for maximum staff accessibility.",
  },
  {
    id: "opp-743-4",
    branchCode: 743,
    name: "Grootvlei Prison",
    province: "Free State",
    department: "Correctional Services",
    latitude: -29.18,
    longitude: 26.25,
    distance: 8.0,
    employees: "400-500",
    minEmployees: 400,
    maxEmployees: 500,
    currentPenetration: 30,
    lastVisit: null,
    visitStatus: "New",
    strategicValue: "Medium",
    keyChallenge: "High Security",
    agentAction: "Schedule formal visits",
    aiInsight: "Key correctional services site. Requires formal engagement strategy due to security protocols.",
  },
  {
    id: "opp-743-5",
    branchCode: 743,
    name: "Universitas Hospital",
    province: "Free State",
    department: "Health",
    latitude: -29.11,
    longitude: 26.18,
    distance: 4.5,
    employees: "1200+",
    minEmployees: 1200,
    maxEmployees: 1500,
    currentPenetration: 90,
    lastVisit: "2025-06-30",
    visitStatus: "Completed",
    strategicValue: "High",
    keyChallenge: "Academic staff",
    agentAction: "Partner with university events",
    aiInsight: "Academic hospital linked to the university. High concentration of skilled professionals.",
  },
  // 721: Durban CBD
  {
    id: "opp-721-1",
    branchCode: 721,
    name: "Addington Hospital",
    province: "Kwa-Zulu Natal",
    department: "Health",
    latitude: -29.86,
    longitude: 31.04,
    distance: 2.5,
    employees: "2000+",
    minEmployees: 2000,
    maxEmployees: 2200,
    currentPenetration: 250,
    lastVisit: "2025-07-19",
    visitStatus: "Follow-up Required",
    strategicValue: "High",
    keyChallenge: "Urban Density",
    agentAction: "Focus on staff entrances",
    aiInsight: "Iconic Durban hospital. Massive captive audience. High potential for volume.",
  },
  {
    id: "opp-721-2",
    branchCode: 721,
    name: "SAPS Durban Central",
    province: "Kwa-Zulu Natal",
    department: "SAPS",
    latitude: -29.85,
    longitude: 31.02,
    distance: 1.0,
    employees: "700-800",
    minEmployees: 700,
    maxEmployees: 800,
    currentPenetration: 150,
    lastVisit: "2025-07-21",
    visitStatus: "Completed",
    strategicValue: "High",
    keyChallenge: "High traffic area",
    agentAction: "Consistent daily presence",
    aiInsight: "One of the busiest stations in the country. Huge potential but requires dedicated agent time.",
  },
  {
    id: "opp-721-3",
    branchCode: 721,
    name: "Durban Magistrate's Court",
    province: "Kwa-Zulu Natal",
    department: "Other",
    latitude: -29.855,
    longitude: 31.022,
    distance: 0.8,
    employees: "300-400",
    minEmployees: 300,
    maxEmployees: 400,
    currentPenetration: 60,
    lastVisit: "2025-07-14",
    visitStatus: "Follow-up Required",
    strategicValue: "Medium",
    keyChallenge: "Professional Staff",
    agentAction: "Offer investment products",
    aiInsight: "High concentration of justice department employees. Tailor offerings for higher income brackets.",
  },
  {
    id: "opp-721-4",
    branchCode: 721,
    name: "KZN Dept. of Health",
    province: "Kwa-Zulu Natal",
    department: "Health",
    latitude: -29.858,
    longitude: 31.01,
    distance: 1.5,
    employees: "600-700",
    minEmployees: 600,
    maxEmployees: 700,
    currentPenetration: 80,
    lastVisit: null,
    visitStatus: "New",
    strategicValue: "High",
    keyChallenge: "Admin Hub",
    agentAction: "Target lunch hours",
    aiInsight: "Provincial admin center for Health. Key decision-makers and administrative staff are based here.",
  },
  {
    id: "opp-721-5",
    branchCode: 721,
    name: "Westville Correctional Centre",
    province: "Kwa-Zulu Natal",
    department: "Correctional Services",
    latitude: -29.83,
    longitude: 30.92,
    distance: 15.0,
    employees: "1000+",
    minEmployees: 1000,
    maxEmployees: 1100,
    currentPenetration: 120,
    lastVisit: "2025-06-25",
    visitStatus: "Completed",
    strategicValue: "High",
    keyChallenge: "High Security",
    agentAction: "Build relationships with staff",
    aiInsight: "Major correctional facility. A large, stable employee base makes it a prime target.",
  },
  // 728: Madiba Street (Pretoria)
  {
    id: "opp-728-1",
    branchCode: 728,
    name: "SAPS Pretoria Central",
    province: "Gauteng",
    department: "SAPS",
    latitude: -25.746,
    longitude: 28.187,
    distance: 2.1,
    employees: "600+",
    minEmployees: 600,
    maxEmployees: 700,
    currentPenetration: 150,
    lastVisit: "2025-07-20",
    visitStatus: "Follow-up Required",
    strategicValue: "High",
    keyChallenge: "High-security area",
    agentAction: "Schedule formal appointments",
    aiInsight: "Major hub with significant potential. Penetration is strong at ~21%. Formal engagements are key.",
  },
  {
    id: "opp-728-2",
    branchCode: 728,
    name: "Steve Biko Academic Hospital",
    province: "Gauteng",
    department: "Health",
    latitude: -25.731,
    longitude: 28.207,
    distance: 4.5,
    employees: "2000+",
    minEmployees: 2000,
    maxEmployees: 2500,
    currentPenetration: 250,
    lastVisit: "2025-07-18",
    visitStatus: "Completed",
    strategicValue: "High",
    keyChallenge: "Multiple entry points",
    agentAction: "Cover staff entrances",
    aiInsight: "Another massive captive audience. Focus on staff-only entrances and exits during shift changes.",
  },
  {
    id: "opp-728-3",
    branchCode: 728,
    name: "Union Buildings",
    province: "Gauteng",
    department: "Other",
    latitude: -25.74,
    longitude: 28.21,
    distance: 3.0,
    employees: "1500+",
    minEmployees: 1500,
    maxEmployees: 2000,
    currentPenetration: 180,
    lastVisit: "2025-07-22",
    visitStatus: "Visit Scheduled",
    strategicValue: "High",
    keyChallenge: "High Profile",
    agentAction: "Professional & discreet approach",
    aiInsight:
      "The seat of government. A prestigious and large employee base. Requires a highly professional approach.",
  },
  {
    id: "opp-728-4",
    branchCode: 728,
    name: "SANDF Headquarters",
    province: "Gauteng",
    department: "SANDF",
    latitude: -25.75,
    longitude: 28.22,
    distance: 5.0,
    employees: "3000+",
    minEmployees: 3000,
    maxEmployees: 4000,
    currentPenetration: 400,
    lastVisit: "2025-07-12",
    visitStatus: "Follow-up Required",
    strategicValue: "High",
    keyChallenge: "Military Hierarchy",
    agentAction: "Engage with base commanders",
    aiInsight: "The largest captive audience in the area. Understanding military structure is key to success.",
  },
  {
    id: "opp-728-5",
    branchCode: 728,
    name: "University of Pretoria",
    province: "Gauteng",
    department: "Education",
    latitude: -25.755,
    longitude: 28.23,
    distance: 6.0,
    employees: "2000+",
    minEmployees: 2000,
    maxEmployees: 2500,
    currentPenetration: 220,
    lastVisit: "2025-07-05",
    visitStatus: "Completed",
    strategicValue: "High",
    keyChallenge: "Dispersed Campus",
    agentAction: "Focus on faculty buildings",
    aiInsight: "A major university with a large, high-income staff base. Focus on specific faculties per visit.",
  },
]

export interface Branch {
  code: number
  city: string
  province: string
  latitude: number
  longitude: number
  status: string
  opportunityScore: string
  strategicActions: string
  insights: string
  medianIncome: number
  avgTravelCost: string
  opportunityClusters: string
}

export const branches: Branch[] = [
  {
    code: 708,
    city: "Bellville",
    province: "Western Cape",
    latitude: -33.903,
    longitude: 18.63,
    status: "VALIDATED",
    opportunityScore: "Valid Branch Opportunity",
    strategicActions: "Maintain current ops; Add 2 agents",
    insights:
      "Dense government cluster with Kuilsrivier (250) + courts + schools; Competition from Capfin but payroll consolidation differentiates; Low travel costs enable multi-site daily visits.",
    medianIncome: 9964.02,
    avgTravelCost: "R35",
    opportunityClusters: "Police-Court-School",
  },
  {
    code: 743,
    city: "Bloemfontein",
    province: "Free State",
    latitude: -29.118,
    longitude: 26.223,
    status: "VACANT",
    opportunityScore: "Low Potential",
    strategicActions: "Leverage provincial capital status",
    insights:
      "Located in CBD near Mimosa Mall with SASSA and Home Affairs nearby; Provincial capital with high concentration of government offices at Hoffman Square; Central location enables easy agent access to institutional offices.",
    medianIncome: 12806.22,
    avgTravelCost: "R40",
    opportunityClusters: "Police-Hospital",
  },
  {
    code: 734,
    city: "Burgersfort",
    province: "Limpopo",
    latitude: -24.666,
    longitude: 30.325,
    status: "NEEDS ANALYSIS",
    opportunityScore: "Needs Further Market Analysis",
    strategicActions: "Monitor for saturation",
    insights:
      "Small town with Department of Labor and Sekhukhune Municipality within 1km; Main road location captures high street traffic; Risk of quick market saturation due to limited town size.",
    medianIncome: 25105.32,
    avgTravelCost: "R55",
    opportunityClusters: "Mining-School",
  },
  {
    code: 753,
    city: "Carletonville",
    province: "Gauteng",
    latitude: -26.358,
    longitude: 27.398,
    status: "HIGH POTENTIAL",
    opportunityScore: "Needs Further Market Analysis",
    strategicActions: "Expand mining sector coverage",
    insights:
      "CBD location directly across from Merafong City Municipality offices; Strong mining town creates dual opportunity; Low competition allows Bayport to dominate payroll consolidation market.",
    medianIncome: 19032.57,
    avgTravelCost: "R45",
    opportunityClusters: "Mining-Police",
  },
  {
    code: 757,
    city: "Doornkop",
    province: "Gauteng",
    latitude: -26.233,
    longitude: 27.816,
    status: "NEEDS ANALYSIS",
    opportunityScore: "Valid Branch Opportunity",
    strategicActions: "Evaluate vs Joburg coverage",
    insights:
      "Overlap with Johannesburg coverage area; High competition; May be redundant with better-positioned branches.",
    medianIncome: 14834.08,
    avgTravelCost: "R50",
    opportunityClusters: "Police-Industrial",
  },
  {
    code: 721,
    city: "Durban CBD",
    province: "Kwa-Zulu Natal",
    latitude: -29.858,
    longitude: 31.029,
    status: "VALIDATED",
    opportunityScore: "Valid Branch Opportunity",
    strategicActions: "Differentiate with payroll focus",
    insights:
      "MSC Building location in heart of government district; High competitor density overcome by unique payroll deduction advantage; Large untapped market as Durban continues expanding.",
    medianIncome: 8783.43,
    avgTravelCost: "R30",
    opportunityClusters: "Police-Court-Hospital",
  },
  {
    code: 705,
    city: "East London",
    province: "Eastern Cape",
    latitude: -33.015,
    longitude: 27.911,
    status: "VALIDATED",
    opportunityScore: "Low Potential",
    strategicActions: "Maintain and optimize",
    insights:
      "Coastal city with university and government offices; Low competition creates opportunity; Good coverage of Eastern Cape.",
    medianIncome: 9451.74,
    avgTravelCost: "R35",
    opportunityClusters: "Police-School-Hospital",
  },
  {
    code: 729,
    city: "Germiston",
    province: "Gauteng",
    latitude: -26.225,
    longitude: 28.17,
    status: "VALIDATED",
    opportunityScore: "Valid Branch Opportunity",
    strategicActions: "Focus on industrial",
    insights:
      "Part of East Rand government cluster; Competition high but market large; Industrial workforce adds opportunity.",
    medianIncome: 12470.0,
    avgTravelCost: "R40",
    opportunityClusters: "Police-Industrial",
  },
  {
    code: 703,
    city: "Gqeberha",
    province: "Eastern Cape",
    latitude: -33.96,
    longitude: 25.602,
    status: "VALIDATED",
    opportunityScore: "Low Potential",
    strategicActions: "Expand to townships",
    insights: "Metro status with Nelson Mandela University; Growing government sector; Township expansion opportunity.",
    medianIncome: 12793.47,
    avgTravelCost: "R32",
    opportunityClusters: "Police-Court-School",
  },
  {
    code: 745,
    city: "Joburg City",
    province: "Gauteng",
    latitude: -26.204,
    longitude: 28.047,
    status: "VALIDATED",
    opportunityScore: "Valid Branch Opportunity",
    strategicActions: "Segment by area",
    insights:
      "Largest opportunity concentration; Despite saturation payroll market sustains presence; Need area specialization.",
    medianIncome: 14834.08,
    avgTravelCost: "R35",
    opportunityClusters: "All sectors",
  },
  {
    code: 732,
    city: "Kimberley",
    province: "Northern Cape",
    latitude: -28.732,
    longitude: 24.762,
    status: "VACANT",
    opportunityScore: "Low Potential",
    strategicActions: "Maintain position",
    insights: "Provincial capital with diamond mining legacy; Limited competition; Stable government employee base.",
    medianIncome: 14676.29,
    avgTravelCost: "R38",
    opportunityClusters: "Police-Mining-Gov",
  },
  {
    code: 820,
    city: "Klerksdorp",
    province: "North West",
    latitude: -26.874,
    longitude: 26.663,
    status: "HIGH POTENTIAL",
    opportunityScore: "Moderate Potential",
    strategicActions: "Expand mining focus",
    insights: "mining creates dual opportunity; Underserved market; Strategic for North West coverage.",
    medianIncome: 10304.1,
    avgTravelCost: "R42",
    opportunityClusters: "Mining-Police-School",
  },
  {
    code: 728,
    city: "Madiba Street",
    province: "Gauteng",
    latitude: -25.746,
    longitude: 28.187,
    status: "VALIDATED",
    opportunityScore: "Valid Branch Opportunity",
    strategicActions: "Coordinate with CBD",
    insights:
      "Part of Pretoria government cluster; Avoid overlap with other Gauteng branches; Focus on specific departments.",
    medianIncome: 15725.92,
    avgTravelCost: "R35",
    opportunityClusters: "Mixed urban",
  },
  {
    code: 712,
    city: "Mbombela",
    province: "Mpumalanga",
    latitude: -25.475,
    longitude: 30.985,
    status: "VALIDATED",
    opportunityScore: "Low Potential",
    strategicActions: "Leverage capital status",
    insights: "Provincial capital advantage; Tourism sector adds private opportunity; Gateway to Mozambique corridor.",
    medianIncome: 9307.8,
    avgTravelCost: "R40",
    opportunityClusters: "Gov-Tourism-Police",
  },
  {
    code: 717,
    city: "Mthatha",
    province: "Eastern Cape",
    latitude: -31.589,
    longitude: 28.789,
    status: "VACANT",
    opportunityScore: "Low Potential",
    strategicActions: "Expand rural coverage",
    insights: "Former homeland capital; Underserved market; Large rural government employee catchment.",
    medianIncome: 12054.81,
    avgTravelCost: "R45",
    opportunityClusters: "Police-School",
  },
  {
    code: 752,
    city: "Northam",
    province: "Limpopo",
    latitude: -24.961,
    longitude: 27.268,
    status: "NEEDS ANALYSIS",
    opportunityScore: "Valid Branch Opportunity",
    strategicActions: "Link to Rustenburg ops",
    insights: "Platinum belt opportunity but overlap with Rustenburg coverage; Consider joint operations model.",
    medianIncome: 29855.32,
    avgTravelCost: "R50",
    opportunityClusters: "Mining-Police",
  },
  {
    code: 9,
    city: "Pietermaritzburg",
    province: "Kwa-Zulu Natal",
    latitude: -29.6,
    longitude: 30.379,
    status: "VALIDATED",
    opportunityScore: "Needs Further Market Analysis",
    strategicActions: "Expand education sector",
    insights: "Provincial capital with major university; Strong government base; Education sector underexploited.",
    medianIncome: 12297.0,
    avgTravelCost: "R32",
    opportunityClusters: "Gov-University-Police",
  },
  {
    code: 742,
    city: "Polokwane",
    province: "Limpopo",
    latitude: -23.905,
    longitude: 29.465,
    status: "VALIDATED",
    opportunityScore: "Low Potential",
    strategicActions: "Strengthen position",
    insights: "Provincial capital , Major government concentration; Hub for Limpopo operations.",
    medianIncome: 11295.63,
    avgTravelCost: "R35",
    opportunityClusters: "All sectors",
  },
  {
    code: 46,
    city: "Rustenburg",
    province: "North West",
    latitude: -25.665,
    longitude: 27.24,
    status: "VALIDATED",
    opportunityScore: "Valid Branch Opportunity",
    strategicActions: "Balance mining/gov",
    insights:
      "Platinum mining center with government offices; Dual-sector opportunity; Strategic for province coverage.",
    medianIncome: 23838.33,
    avgTravelCost: "R38",
    opportunityClusters: "Mining-Police-Gov",
  },
  {
    code: 19,
    city: "Welkom",
    province: "Free State",
    latitude: -27.983,
    longitude: 26.733,
    status: "HIGH POTENTIAL",
    opportunityScore: "Moderate Potential",
    strategicActions: "Revive with mining focus",
    insights:
      "mining town with untapped potential; Link to Bloemfontein operations; Government offices and poential in town.",
    medianIncome: 12279.83,
    avgTravelCost: "R42",
    opportunityClusters: "Mining-Police",
  },
  {
    code: 722,
    city: "Wynberg",
    province: "Western Cape",
    latitude: -34.0,
    longitude: 18.466,
    status: "VALIDATED",
    opportunityScore: "Valid Branch Opportunity",
    strategicActions: "Specialize military",
    insights:
      "Southern suburbs cluster including military bases; Schools and Office Parks Competition from Cape Town CBD; Niche opportunity in military.",
    medianIncome: 9964.02,
    avgTravelCost: "R30",
    opportunityClusters: "Police-Military-School",
  },
]
